Skeleton and Weapon Equip
garry911128/Sylvaar pull request #11
Opened 2024-12-24 16:36 UTC by garry911128

Complete
1. Attack with Sword(no animation), Bomb(no throw)
2. Skeleton of Squirrel that can connect with Weapon(I intentionally placed the weapon in front of the hand so that the player's hitbox would not conflict with the weapon.)
3. Attack enemy.

2024-12-24 16:40 UTC, cuchaos commented on Assets/Scripts/Core/Camera/CameraController.cs
> +            // ����ƹ����ʿ�J
english?

2024-12-24 16:40 UTC, cuchaos commented on Assets/Scripts/Core/Camera/CameraController.cs
> +            // �ˬd�O�_Ĳ�o Lock On
same above

2024-12-24 16:51 UTC, kyynk requested changes
**The namespace should match the folder name.**

P.S. Please remove all `Chinese` comments, they will cause encoding issues.

2024-12-24 16:51 UTC, kyynk commented on Assets/Scripts/Core/Camera/CameraController.cs
The namespace does not match the location.
If you want the file at this location, your namespace should be `Core.Camera`.
If you want the namespace to be `Entities.Player`, you need to move this file under the Player folder.

2024-12-25 02:14 UTC, garry911128 commented on Assets/Scripts/Core/Camera/CameraController.cs
> +            // �ˬd�O�_Ĳ�o Lock On
fix

2024-12-25 02:14 UTC, garry911128 commented on Assets/Scripts/Core/Camera/CameraController.cs
fix

2024-12-25 05:20 UTC, garry911128 commented on Assets/Scripts/Core/Camera/CameraController.cs
> +            // ����ƹ����ʿ�J
fix

2024-12-25 05:56 UTC, kyynk requested changes

2024-12-25 05:56 UTC, kyynk commented on Assets/Scripts/KeyboardInput/KeyboardInputManager.cs
> +            }
remove `Chinese` comments

2024-12-25 06:26 UTC, kyynk approved these changes

2024-12-25 06:33 UTC, merged